[package]
name = "webreg_scraper"
version = "0.3.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.17.0", features = ["macros"] }
webweg = "0.7.1"
chrono = "0.4.19"
once_cell = "1.10.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }

[profile.release]
lto = true
panic = "abort"
opt-level = 3

[features]
default = []
git_repeat = []