[package]
name = "ucsd_webreg_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.59"
reqwest = "0.11.9"
tokio = { version = "1.15.0", features = ["macros"] }
url = "2.2.2"