[package]
name = "ucsd_webreg_rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
reqwest = "0.11.9"
tokio = { version = "1.16.1", features = ["macros"] }
url = "2.2.2"
chrono = "0.4.19"

[profile.release]
lto = true
panic = "abort"
opt-level = 3