[package]
name = "webreg_scraper"
version = "0.4.5"
authors = ["Edward Wang"]
edition = "2021"
description = "A scraper and/or API for UC San Diego's WebReg enrollment system."
repository = "https://github.com/ewang2002/webreg_scraper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "signal", "time"] }
webweg = "0.7.2"
chrono = "0.4.19"
once_cell = "1.10.0"
axum = { version = "0.6.1", optional = true }
tracing = "0.1"
tracing-subscriber = "0.3"
axum-macros = { version = "0.3.0", optional = true }

[dev-dependencies]
axum-macros = "0.3.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 3

[features]
default = ["scraper", "api"]
scraper = []
api = ["dep:axum", "dep:axum-macros"]
