name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  validate_features:
    name: ${{ matrix.feature }} only / compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: ["api", "scraper"]

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check --no-default-features --features ${{ matrix.feature }}
      - name: Clippy
        run: cargo clippy --all-targets --all-features --no-default-features --features ${{ matrix.feature }}

  validate_general:
    name: general / compilation & style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features

      # Don't use clippy-check for now as it is currently using a deprecated version of Node.
      # - name: Clippy
      #   uses: actions-rs/clippy-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     args: --all-targets --all-features
